/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/screen.gltf -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/screen.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode" />
        <group name="RootNode001" />
        <group name="RootNode002" position={[-1.5, 0, -1.6]} scale={2.54} />
        <group name="tmpobj" position={[0.2, 1, -1.4]} scale={0.133} />
        <group name="character" position={[0.013, -0.589, -0.967]} rotation={[-Math.PI, 1.325, -Math.PI]} />
        <group name="Plane">
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.Default} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.Walls} />
          <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.Floor} />
        </group>
        <group name="Laptop" position={[-0.8, 0.72, -1.65]} rotation={[0, 0.525, 0]}>
          <mesh name="ChamferBox017_1" geometry={nodes.ChamferBox017_1.geometry} material={materials['03___Default']} />
          <mesh name="ChamferBox017_1_1" geometry={nodes.ChamferBox017_1_1.geometry} material={materials['05___Default']} />
          <mesh name="ChamferBox017_1_2" geometry={nodes.ChamferBox017_1_2.geometry} material={materials['01___Default']} />
          <mesh name="ChamferBox017_1_3" geometry={nodes.ChamferBox017_1_3.geometry} material={materials['04___Default']} />
        </group>
        <mesh name="ComputerMouse_mesh" geometry={nodes.ComputerMouse_mesh.geometry} material={materials.ComputerMouse_mat1} position={[0.47, 0.72, -1.15]} rotation={[-Math.PI, 0.4, -Math.PI]} scale={0.52} />
        <group name="WallShelf" position={[-1.029, 1.644, -1.865]} rotation={[-2.153, -1.564, -2.147]}>
          <mesh name="Cube-Mesh" geometry={nodes['Cube-Mesh'].geometry} material={materials['1A1A1A']} />
          <mesh name="Cube-Mesh_1" geometry={nodes['Cube-Mesh_1'].geometry} material={materials['Material.001']} />
        </group>
        <group name="Desk" position={[-0.1, 0, -1.5]} rotation={[0, -1.542, 0]}>
          <mesh name="Cylinder010_Cylinder010_BlackCoatSteel" geometry={nodes.Cylinder010_Cylinder010_BlackCoatSteel.geometry} material={materials.BlackCoatSteel} />
          <mesh name="Cylinder010_Cylinder010_BlackCoatSteel_1" geometry={nodes.Cylinder010_Cylinder010_BlackCoatSteel_1.geometry} material={materials.GrayPlastic} />
          <mesh name="Cylinder010_Cylinder010_BlackCoatSteel_2" geometry={nodes.Cylinder010_Cylinder010_BlackCoatSteel_2.geometry} material={materials.BlackPlastic} />
          <mesh name="Cylinder010_Cylinder010_BlackCoatSteel_3" geometry={nodes.Cylinder010_Cylinder010_BlackCoatSteel_3.geometry} material={materials.BlackWood} />
        </group>
        <mesh name="Geo_Penguin" geometry={nodes.Geo_Penguin.geometry} material={materials.lambert2SG} position={[-0.85, 1.92, -1.9]} />
        <group name="Flowers" position={[-1.034, 1.808, -1.886]}>
          <mesh name="mesh434744387" geometry={nodes.mesh434744387.geometry} material={materials.mat14} />
          <mesh name="mesh434744387_1" geometry={nodes.mesh434744387_1.geometry} material={materials.mat8} />
          <mesh name="mesh434744387_2" geometry={nodes.mesh434744387_2.geometry} material={materials.mat12} />
          <mesh name="mesh434744387_3" geometry={nodes.mesh434744387_3.geometry} material={materials.mat10} />
          <mesh name="mesh434744387_4" geometry={nodes.mesh434744387_4.geometry} material={materials['mat20.001']} />
          <mesh name="mesh434744387_5" geometry={nodes.mesh434744387_5.geometry} material={materials.mat24} />
        </group>
        <group name="Axe" position={[-0.72, 0.9, 1.4]} rotation={[2.223, -0.38, -0.452]}>
          <mesh name="mesh1736064932" geometry={nodes.mesh1736064932.geometry} material={materials.mat17} />
          <mesh name="mesh1736064932_1" geometry={nodes.mesh1736064932_1.geometry} material={materials.mat20} />
          <mesh name="mesh1736064932_2" geometry={nodes.mesh1736064932_2.geometry} material={materials.mat19} />
        </group>
        {/* <mesh name="iMac" geometry={nodes.iMac.geometry} material={materials['Mat.001']} position={[0.36, 0.72, -1.7]} rotation={[Math.PI, -1.309, Math.PI]} /> */}
        <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={materials.Mat} position={[0.217, 0.72, -1.369]} rotation={[0, -0.461, 0]} scale={0.726} />
        <group name="WallCube" position={[0.9, 2.1, -1.9]} rotation={[0, 0, -0.734]}>
          <mesh name="Node-Mesh004" geometry={nodes['Node-Mesh004'].geometry} material={materials['mat8.001']} />
          <mesh name="Node-Mesh004_1" geometry={nodes['Node-Mesh004_1'].geometry} material={materials.mat21} />
        </group>
        <mesh name="TreeStump" geometry={nodes.TreeStump.geometry} material={materials.lambert26SG} position={[-0.739, -0.002, 1.499]} />
        <group name="palm_tree_01" position={[1.705, -0.375, -0.906]} rotation={[-3.052, 1.442, 3.088]}>
          <mesh name="palm_tree_01-Mesh" geometry={nodes['palm_tree_01-Mesh'].geometry} material={materials['795548']} />
          <mesh name="palm_tree_01-Mesh_1" geometry={nodes['palm_tree_01-Mesh_1'].geometry} material={materials['8BC34A.001']} />
          <mesh name="palm_tree_01-Mesh_2" geometry={nodes['palm_tree_01-Mesh_2'].geometry} material={materials['DD9944.001']} />
        </group>
        <group name="OfficeChair" position={[-0.029, 0, -0.812]} rotation={[-Math.PI / 2, 0, 2.31]}>
          <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
          <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
          <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
        </group>
        <mesh name="Potted_Plant000" geometry={nodes.Potted_Plant000.geometry} material={materials.Material} position={[-1.5, 0, -1.6]} />
        <mesh name="RubberDuck_mesh" geometry={nodes.RubberDuck_mesh.geometry} material={materials.RubberDuck_mat1} position={[-0.9, 0.72, -1.2]} rotation={[0, 0.537, 0]} />
        <mesh name="TrianglePalmTree_Mesh" geometry={nodes.TrianglePalmTree_Mesh.geometry} material={materials.TrianglePalmTree_mat} position={[-1.296, 1.724, -1.93]} />
        <group name="Wall_Art_Classical_Plane" position={[-2.013, 1.321, 0.058]}>
          <mesh name="Wall_Art_Classical_Plane-Mesh" geometry={nodes['Wall_Art_Classical_Plane-Mesh'].geometry} material={materials.DD9944} />
          <mesh name="Wall_Art_Classical_Plane-Mesh_1" geometry={nodes['Wall_Art_Classical_Plane-Mesh_1'].geometry} material={materials['1A1A1A']} />
          <mesh name="Wall_Art_Classical_Plane-Mesh_2" geometry={nodes['Wall_Art_Classical_Plane-Mesh_2'].geometry} material={materials['4CAF50']} />
          <mesh name="Wall_Art_Classical_Plane-Mesh_3" geometry={nodes['Wall_Art_Classical_Plane-Mesh_3'].geometry} material={materials['8BC34A']} />
        </group>
        <mesh name="Screen"  geometry={nodes.Screen.geometry} material={materials['Mat.001']} position={[0.36, 0.72, -1.7]} rotation={[Math.PI, -1.309, Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/screen.gltf')
