/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture, useVideoTexture } from "@react-three/drei";
import * as THREE from "three"
import { motion } from "framer-motion-3d";
import { animate, useMotionValue } from "framer-motion";
import { useFrame } from "@react-three/fiber";

export function Office(props) {

  const { section } = props;
  const { nodes, materials } = useGLTF("models/scene.gltf");
  const texture = useTexture("textures/baked.jpg"); // we will need a material to use the texture
  const textureVSCode = useVideoTexture("textures/vscode.mp4")
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding; // to tell how the texture is baked

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture 
  });

  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: .42,
  })

  // const videoMaterial = new THREE.MeshStandardMaterial({
  //   map: textureVSCode,
  // })

  const textureOpacity = useMotionValue(0);

  useEffect(() => {
    animate(textureOpacity, section === 0 ? 1 : 0), {
      duration: 0.8,
    };
  }, [section])

  // update on every frame the opacity of the texture
  useFrame(() => {
    textureMaterial.opacity = textureOpacity.get();
  })

  return (
    // The Model after remainking of the Office
    <group {...props} dispose={null}>
    <group name="Scene">
      <group name="Character" position={[0.783, 0.004, -0.222]} rotation={[-Math.PI, 0.399, -Math.PI]} />
      <group name="Desk" position={[0.511, -0.002, -1.21]} rotation={[Math.PI, -1.561, Math.PI]}>
        <mesh name="Cube001_Cube002_BlackCoatSteel" geometry={nodes.Cube001_Cube002_BlackCoatSteel.geometry} material={textureMaterial} />
        <mesh name="Cube001_Cube002_BlackCoatSteel_1" geometry={nodes.Cube001_Cube002_BlackCoatSteel_1.geometry} material={textureMaterial} />
        <mesh name="Cube001_Cube002_BlackCoatSteel_2" geometry={nodes.Cube001_Cube002_BlackCoatSteel_2.geometry} material={textureMaterial} />
        <mesh name="Cube001_Cube002_BlackCoatSteel_3" geometry={nodes.Cube001_Cube002_BlackCoatSteel_3.geometry} material={textureMaterial} />
        <mesh name="Cube001_Cube002_BlackCoatSteel_4" geometry={nodes.Cube001_Cube002_BlackCoatSteel_4.geometry} material={textureMaterial} />
      </group>
      <group name="Shelf" position={[-0.622, 1.73, -1.518]}>
        <mesh name="SM_ShelfSM_Shelf1_1" geometry={nodes.SM_ShelfSM_Shelf1_1.geometry} material={textureMaterial} />
        <mesh name="SM_ShelfSM_Shelf1_1_1" geometry={nodes.SM_ShelfSM_Shelf1_1_1.geometry} material={textureMaterial} />
      </group>
      <group name="OfficeChair" position={[0.65, 0.002, -0.328]} rotation={[-Math.PI / 2, 0, 3.018]}>
        <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={textureMaterial} />
        <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={textureMaterial} />
        <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={textureMaterial} />
      </group>
      <group name="Lamp" position={[-0.946, 1.979, -1.5]} rotation={[0, 0.527, 0]}>
        <mesh name="Desk_lamp_01_Circle001-Mesh" geometry={nodes['Desk_lamp_01_Circle001-Mesh'].geometry} material={textureMaterial} />
        <mesh name="Desk_lamp_01_Circle001-Mesh_1" geometry={nodes['Desk_lamp_01_Circle001-Mesh_1'].geometry} material={textureMaterial} />
        <mesh name="Desk_lamp_01_Circle001-Mesh_2" geometry={nodes['Desk_lamp_01_Circle001-Mesh_2'].geometry} material={textureMaterial} />
      </group>
      <group name="Laptop" position={[0.069, 0.854, -1.342]} rotation={[0, 0.238, 0]}>
        <mesh name="ChamferBox017_1" geometry={nodes.ChamferBox017_1.geometry} material={textureMaterial} />
        <mesh name="ChamferBox017_1_1" geometry={nodes.ChamferBox017_1_1.geometry} material={textureMaterial} />
        <mesh name="ChamferBox017_1_2" geometry={nodes.ChamferBox017_1_2.geometry} material={textureMaterial} />
        <mesh name="ChamferBox017_1_3" geometry={nodes.ChamferBox017_1_3.geometry} material={textureMaterial} />
      </group>
      <mesh name="RubberDuck_mesh" geometry={nodes.RubberDuck_mesh.geometry} material={textureMaterial} position={[-0.326, 0.834, -0.918]} rotation={[0, 1.156, 0]} />
      <group name="Wall_Art_Classical_Plane" position={[-1.785, 1.288, 0.34]} rotation={[Math.PI, -1.57, Math.PI]}>
        <mesh name="Wall_Art_Classical_Plane-Mesh" geometry={nodes['Wall_Art_Classical_Plane-Mesh'].geometry} material={textureMaterial} />
        <mesh name="Wall_Art_Classical_Plane-Mesh_1" geometry={nodes['Wall_Art_Classical_Plane-Mesh_1'].geometry} material={textureMaterial} />
        <mesh name="Wall_Art_Classical_Plane-Mesh_2" geometry={nodes['Wall_Art_Classical_Plane-Mesh_2'].geometry} material={textureMaterial} />
        <mesh name="Wall_Art_Classical_Plane-Mesh_3" geometry={nodes['Wall_Art_Classical_Plane-Mesh_3'].geometry} material={textureMaterial} />
      </group>
      <group name="Houseplant_7" position={[-1.092, -0.001, -0.774]} rotation={[-Math.PI / 2, 0, 2.587]}>
        <mesh name="Houseplant_7_1" geometry={nodes.Houseplant_7_1.geometry} material={textureMaterial} />
        <mesh name="Houseplant_7_2" geometry={nodes.Houseplant_7_2.geometry} material={textureMaterial} />
        <mesh name="Houseplant_7_3" geometry={nodes.Houseplant_7_3.geometry} material={textureMaterial} />
      </group>
      <mesh name="Door" geometry={nodes.Door.geometry} material={textureMaterial} position={[-2.036, 1.21, 1.25]} rotation={[-Math.PI, 1.569, -Math.PI]} />
      <group name="Window" position={[-2.048, 1.599, -0.85]} rotation={[Math.PI, -1.567, Math.PI]}>
        <mesh name="mesh1198767915" geometry={nodes.mesh1198767915.geometry} material={textureGlassMaterial} />
        <mesh name="mesh1198767915_1" geometry={nodes.mesh1198767915_1.geometry} material={textureMaterial} />
        <mesh name="mesh1198767915_2" geometry={nodes.mesh1198767915_2.geometry} material={textureMaterial} />
      </group>
      <group name="Mantis" position={[-0.388, 2.232, -1.374]} rotation={[-Math.PI, 0.045, -Math.PI]}>
        <mesh name="Node-Mesh003" geometry={nodes['Node-Mesh003'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh003_1" geometry={nodes['Node-Mesh003_1'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh003_2" geometry={nodes['Node-Mesh003_2'].geometry} material={textureMaterial} />
      </group>
      <group name="Cube" position={[1.421, 2.373, -1.6]} rotation={[0, 0, -0.85]}>
        <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={textureMaterial} />
        <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={textureMaterial} />
      </group>
      <group name="Mouse" position={[1.227, 0.847, -0.82]} rotation={[-1.563, 0.003, -0.311]}>
        <mesh name="cuerpo_base_mouse" geometry={nodes.cuerpo_base_mouse.geometry} material={textureMaterial} />
        <mesh name="cuerpo_base_mouse_1" geometry={nodes.cuerpo_base_mouse_1.geometry} material={textureMaterial} />
        <mesh name="cuerpo_base_mouse_2" geometry={nodes.cuerpo_base_mouse_2.geometry} material={textureMaterial} />
        <mesh name="cuerpo_base_mouse_3" geometry={nodes.cuerpo_base_mouse_3.geometry} material={textureMaterial} />
      </group>
      <mesh name="Keyboard001" geometry={nodes.Keyboard001.geometry} material={textureMaterial} position={[0.859, 0.847, -0.911]} rotation={[0, -0.269, 0]} />
      <group name="Dog" position={[-0.021, 0, 1.016]} rotation={[0, 0.403, 0]}>
        <mesh name="Dog-Mesh" geometry={nodes['Dog-Mesh'].geometry} material={textureMaterial} />
        <mesh name="Dog-Mesh_1" geometry={nodes['Dog-Mesh_1'].geometry} material={textureMaterial} />
        <mesh name="Dog-Mesh_2" geometry={nodes['Dog-Mesh_2'].geometry} material={textureMaterial} />
        <mesh name="Dog-Mesh_3" geometry={nodes['Dog-Mesh_3'].geometry} material={textureMaterial} />
      </group>
      <group name="Cat" position={[1.974, 0.002, -0.303]} rotation={[0, 1.018, 0]}>
        <mesh name="Cube004-Mesh" geometry={nodes['Cube004-Mesh'].geometry} material={textureMaterial} />
        <mesh name="Cube004-Mesh_1" geometry={nodes['Cube004-Mesh_1'].geometry} material={textureMaterial} />
        <mesh name="Cube004-Mesh_2" geometry={nodes['Cube004-Mesh_2'].geometry} material={textureMaterial} />
        <mesh name="Cube004-Mesh_3" geometry={nodes['Cube004-Mesh_3'].geometry} material={textureMaterial} />
        <mesh name="Cube004-Mesh_4" geometry={nodes['Cube004-Mesh_4'].geometry} material={textureMaterial} />
        <mesh name="Cube004-Mesh_5" geometry={nodes['Cube004-Mesh_5'].geometry} material={textureMaterial} />
      </group>
      <group name="Monitor" position={[0.966, 1.003, -1.319]} rotation={[Math.PI, -1.543, Math.PI]} scale={1.221}>
        {/* <mesh name="mesh941242678007" geometry={nodes.mesh941242678007.geometry} material={textureMaterial} /> */}
        <mesh name="mesh941242678007_1" geometry={nodes.mesh941242678007_1.geometry} material={textureMaterial} />
      </group>
      <mesh name="Screen" 
          geometry={nodes.Screen.geometry} 
          // material={videoMaterial} 
          position={[0.966, 1.003, -1.319]} 
          rotation={[Math.PI, -1.543, Math.PI]} 
          scale={1.221} 
        >
         <meshBasicMaterial map={textureVSCode} toneMapped={false} />
        </mesh>
      <group name="Plane" position={[0.219, -0.197, 0.026]}>
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={textureMaterial} />
        <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={textureMaterial} />
        <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={textureMaterial} />
      </group>
    </group>
  </group>
    // The Model before Remaking of the Office
    // <group {...props} dispose={null}>
    //   <group name="Scene"> 
    //   {/* <mesh name="Screen" 
    //     geometry={nodes.Screen.geometry} 
    //     // we need to create a special material containing the video texture
    //     // material={nodes.Screen.material} // taken out -> and used as (as what sis?)
    //     position={[0.36, 0.72, -1.7]} 
    //     rotation={[Math.PI, -1.309, Math.PI]} 
    //   >
    //     <meshBasicMaterial map={textureVSCode} toneMapped={false} />
    //   </mesh> */}
    //     <mesh 
    //       name="Screen" 
    //       geometry={nodes.Screen.geometry} 
    //       // material={materials['Mat.001']} 
    //       position={[0.36, 0.72, -1.7]} 
    //       rotation={[Math.PI, -1.309, Math.PI]} 
    //     >
    //       <meshBasicMaterial map={textureVSCode} toneMapped={false} />
    //     </mesh>

    //     <group name="RootNode" />
    //     <group name="RootNode001" />
    //     <group name="RootNode002" position={[-1.5, 0, -1.6]} scale={2.54} />
    //     <group name="tmpobj" position={[0.2, 1, -1.4]} scale={0.133} />
    //     <group name="character" 
    //     // position={[0.013, -0.589, -0.967]} rotation={[-Math.PI, 1.325, -Math.PI]} 
    //     />
    //     <group name="Plane">
    //       <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={textureMaterial} />
    //       <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={textureMaterial} />
    //       <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={textureMaterial} />
    //     </group>
    //     <motion.group
    //     scale={[0, 0, 0]}
    //     animate={{ 
    //       scale: section === 0 ? 1 : 0,
    //     }}
    //      name="Laptop" position={[-0.8, 0.72, -1.65]} rotation={[0, 0.525, 0]}>
    //       <mesh name="ChamferBox017_1" geometry={nodes.ChamferBox017_1.geometry} material={textureMaterial} />
    //       <mesh name="ChamferBox017_1_1" geometry={nodes.ChamferBox017_1_1.geometry} material={textureMaterial} />
    //       <mesh name="ChamferBox017_1_2" geometry={nodes.ChamferBox017_1_2.geometry} material={textureMaterial} />
    //       <mesh name="ChamferBox017_1_3" geometry={nodes.ChamferBox017_1_3.geometry} material={textureMaterial} />
    //     </motion.group>
    //     <mesh name="ComputerMouse_mesh" geometry={nodes.ComputerMouse_mesh.geometry} material={textureMaterial} position={[0.47, 0.72, -1.15]} rotation={[-Math.PI, 0.4, -Math.PI]} scale={0.52} />
    //     <group name="WallShelf" position={[-1.029, 1.644, -1.865]} rotation={[-2.153, -1.564, -2.147]}>
    //       <mesh name="Cube-Mesh" geometry={nodes['Cube-Mesh'].geometry} material={textureMaterial} />
    //       <mesh name="Cube-Mesh_1" geometry={nodes['Cube-Mesh_1'].geometry} material={textureMaterial} />
    //     </group>
    //     <motion.group
    //       scale={[0, 0, 0]}
    //       animate={{ 
    //         scale: section === 0 ? 1 : 0,
    //       }}
    //      name="Desk" position={[-0.1, 0, -1.5]} rotation={[0, -1.542, 0]}>
    //       <mesh name="Cylinder010_Cylinder010_BlackCoatSteel" geometry={nodes.Cylinder010_Cylinder010_BlackCoatSteel.geometry} material={textureMaterial} />
    //       <mesh name="Cylinder010_Cylinder010_BlackCoatSteel_1" geometry={nodes.Cylinder010_Cylinder010_BlackCoatSteel_1.geometry} material={textureMaterial} />
    //       <mesh name="Cylinder010_Cylinder010_BlackCoatSteel_2" geometry={nodes.Cylinder010_Cylinder010_BlackCoatSteel_2.geometry} material={textureMaterial} />
    //       <mesh name="Cylinder010_Cylinder010_BlackCoatSteel_3" geometry={nodes.Cylinder010_Cylinder010_BlackCoatSteel_3.geometry} material={textureMaterial} />
    //     </motion.group>
    //     <mesh name="Geo_Penguin" geometry={nodes.Geo_Penguin.geometry} material={textureMaterial} position={[-0.85, 1.92, -1.9]} />
    //     <group name="Flowers" position={[-1.034, 1.808, -1.886]}>
    //       <mesh name="mesh434744387" geometry={nodes.mesh434744387.geometry} material={textureMaterial} />
    //       <mesh name="mesh434744387_1" geometry={nodes.mesh434744387_1.geometry} material={textureMaterial} />
    //       <mesh name="mesh434744387_2" geometry={nodes.mesh434744387_2.geometry} material={textureMaterial} />
    //       <mesh name="mesh434744387_3" geometry={nodes.mesh434744387_3.geometry} material={textureMaterial} />
    //       <mesh name="mesh434744387_4" geometry={nodes.mesh434744387_4.geometry} material={textureMaterial} />
    //       <mesh name="mesh434744387_5" geometry={nodes.mesh434744387_5.geometry} material={textureMaterial} />
    //     </group>
    //     <motion.group
    //       scale={[0, 0, 0]}
    //       animate={{ 
    //         scale: section === 0 ? 1 : 0,
    //       }}
    //      name="Axe" position={[-0.72, 0.9, 1.4]} rotation={[2.223, -0.38, -0.452]}>
    //       <mesh name="mesh1736064932" geometry={nodes.mesh1736064932.geometry} material={textureMaterial} />
    //       <mesh name="mesh1736064932_1" geometry={nodes.mesh1736064932_1.geometry} material={textureMaterial} />
    //       <mesh name="mesh1736064932_2" geometry={nodes.mesh1736064932_2.geometry} material={textureMaterial} />
    //     </motion.group>


    //     <motion.mesh
    //       scale={[0, 0, 0]}
    //       animate={{ 
    //         scale: section === 0 ? 1 : 0,
    //       }}
    //      name="iMac" 
    //      geometry={nodes.iMac.geometry} 
    //      material={textureMaterial} 
    //      position={[0.36, 0.72, -1.7]} 
    //      rotation={[Math.PI, -1.309, Math.PI]} 
    //      />

         
    //     <mesh name="Keyboard" geometry={nodes.Keyboard.geometry} material={textureMaterial} position={[0.217, 0.72, -1.369]} rotation={[0, -0.461, 0]} scale={0.726} />
    //     <group name="WallCube" position={[0.9, 2.1, -1.9]} rotation={[0, 0, -0.734]}>
    //       <mesh name="Node-Mesh004" geometry={nodes['Node-Mesh004'].geometry} material={textureMaterial} />
    //       <mesh name="Node-Mesh004_1" geometry={nodes['Node-Mesh004_1'].geometry} material={textureMaterial} />
    //     </group>
    //     <motion.mesh
    //       scale={[0, 0, 0]}
    //       animate={{ 
    //         scale: section === 0 ? 1 : 0,
    //       }}
    //      name="TreeStump" geometry={nodes.TreeStump.geometry} material={textureMaterial} position={[-0.739, -0.002, 1.499]} />
    //     <motion.group
    //       scale={[0, 0, 0]}
    //       animate={{ 
    //         scale: section === 0 ? 1 : 0,
    //       }}
    //      name="palm_tree_01" position={[1.705, -0.375, -0.906]} rotation={[-3.052, 1.442, 3.088]}>
    //       <mesh name="palm_tree_01-Mesh" geometry={nodes['palm_tree_01-Mesh'].geometry} material={textureMaterial} />
    //       <mesh name="palm_tree_01-Mesh_1" geometry={nodes['palm_tree_01-Mesh_1'].geometry} material={textureMaterial} />
    //       <mesh name="palm_tree_01-Mesh_2" geometry={nodes['palm_tree_01-Mesh_2'].geometry} material={textureMaterial} />
    //     </motion.group>
    //     <motion.group
    //       scale={[0, 0, 0]}
    //       animate={{ 
    //         scale: section === 0 ? 1 : 0,
    //       }}
    //      name="OfficeChair" position={[-0.029, 0, -0.812]} rotation={[-Math.PI / 2, 0, 2.31]}>
    //       <mesh name="OfficeChair_1" geometry={nodes.OfficeChair_1.geometry} material={textureMaterial} />
    //       <mesh name="OfficeChair_2" geometry={nodes.OfficeChair_2.geometry} material={textureMaterial} />
    //       <mesh name="OfficeChair_3" geometry={nodes.OfficeChair_3.geometry} material={textureMaterial} />
    //     </motion.group>
    //     <mesh name="Potted_Plant000" geometry={nodes.Potted_Plant000.geometry} material={textureMaterial} position={[-1.5, 0, -1.6]} />
    //     <motion.mesh
    //       scale={[0, 0, 0]}
    //       animate={{ 
    //         scale: section === 0 ? 1 : 0,
    //       }}
    //      name="RubberDuck_mesh" geometry={nodes.RubberDuck_mesh.geometry} material={textureMaterial} position={[-0.9, 0.72, -1.2]} rotation={[0, 0.537, 0]} />
    //     <mesh name="TrianglePalmTree_Mesh" geometry={nodes.TrianglePalmTree_Mesh.geometry} material={textureMaterial} position={[-1.296, 1.724, -1.93]} />
    //     <motion.group
    //       scale={[0, 0, 0]}
    //       animate={{ 
    //         scale: section === 0 ? 1 : 0,
    //       }}
    //      name="Wall_Art_Classical_Plane" position={[-2.013, 1.321, 0.058]}>
    //       <mesh name="Wall_Art_Classical_Plane-Mesh" geometry={nodes['Wall_Art_Classical_Plane-Mesh'].geometry} material={textureMaterial} />
    //       <mesh name="Wall_Art_Classical_Plane-Mesh_1" geometry={nodes['Wall_Art_Classical_Plane-Mesh_1'].geometry} material={textureMaterial} />
    //       <mesh name="Wall_Art_Classical_Plane-Mesh_2" geometry={nodes['Wall_Art_Classical_Plane-Mesh_2'].geometry} material={textureMaterial} />
    //       <mesh name="Wall_Art_Classical_Plane-Mesh_3" geometry={nodes['Wall_Art_Classical_Plane-Mesh_3'].geometry} material={textureMaterial} />
    //     </motion.group>
    //   </group>
    // </group>
  );
}

useGLTF.preload("models/scene.gltf");
useTexture.preload("textures/baked.jpg");